allow-licenses:
  - 0BSD
  - AGPL-3.0
  - AGPL-3.0-only
  - Apache-2.0
  - BlueOak-1.0.0
  - BSD-2-Clause
  - BSD-3-Clause
  - CC-BY-4.0
  - CC0-1.0
  - FTL
  - GPL-2.0-or-later
  - GPL-3.0
  - ISC
  - LGPL-3.0
  - MIT
  - MIT-0
  - MPL-2.0
  - Python-2.0
  - Unlicense
  - X11
allow-dependencies-licenses:
  - pkg:npm/canvas@3.1.2
  - pkg:npm/cookie-signature@1.2.2
  - pkg:npm/mongoose-lean-virtuals@2.0.0
